### ISSUE TITLE
[raven_front] Background Network Activity

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#10]
### Describe The User Story

As a user I want to see that background activity is happening So that I know my device is getting data.

As a Dev I want to see that background activity is happening So that I know the client device is communicating with the server.

### Tasks For This Story
 - [x] https://github.com/moontreeapp/raven_front/issues/43
 - [x] https://github.com/moontreeapp/raven_front/issues/42
 - [ ] hide this for MVP

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced with [Backdrop](https://github.com/moontreeapp/moontree/issues/279)
