### ISSUE TITLE
Code Management

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#16]
**Describe the User Story:**
As a new developer
I want to know what this moontree thing is all about as easily as possible

**Describe What You'd Like:**
this means simple and uniform github practices

**Tasks:**
- [X] set up labels, issue templates, and projects
- [ ] https://github.com/moontreeapp/raven_front/issues/49
- [ ] https://github.com/moontreeapp/raven_front/issues/45
- [x] https://github.com/moontreeapp/raven_back/issues/51
