### ISSUE TITLE
[raven_front] Backend Server

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#17]
**Describe the User Story:**
As a MoonTree
I want my own electrum server
So that I can optimize certain things and offer special abilities

**Describe What You'd Like:**
A server with ravend for both mainnet and testnet, electrum for each, ipfs pinning service, and possibly more. everything should be dockerized.

**Tasks:**
- [x] https://github.com/moontreeapp/raven_back/issues/1
- [ ] https://github.com/moontreeapp/raven_server/issues/1
- [ ] https://github.com/moontreeapp/raven_server/issues/2
- [ ] https://github.com/moontreeapp/raven_server/issues/3

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Backend Docker Image](https://github.com/moontreeapp/moontree/issues/252)
