### ISSUE TITLE
[raven_front] User Security

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#18]
**Describe the User Story:**
As a User
I want to control the level of security I'm happy with

**Stories**
- [ ] https://github.com/moontreeapp/raven_back/issues/41

**Tasks:**
- [x] https://github.com/moontreeapp/raven_back/issues/16
- [x] https://github.com/moontreeapp/raven_back/issues/37
- [x] https://github.com/moontreeapp/raven_front/issues/13
- [x] https://github.com/moontreeapp/raven_back/issues/39
- [x] https://github.com/moontreeapp/raven_back/issues/28
