### ISSUE TITLE
[raven_front] Home Screen

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#19]
**Describe the User Story:**
As a User
I want to see everything I hold on the homescreen
So that I know what I have

**Describe What You'd Like:**
I should be able to: see name, see logo, see balance, see transactions, see differentiation of unique vs master asset,

**Stories**
- [x] https://github.com/moontreeapp/raven_front/issues/72

**Tasks:**
- [x] https://github.com/moontreeapp/raven_front/issues/67
- [x] https://github.com/moontreeapp/raven_front/issues/66
- [ ] https://github.com/moontreeapp/raven_front/issues/85
- [x] https://github.com/moontreeapp/raven_front/issues/65
- [x] https://github.com/moontreeapp/raven_front/issues/68

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Wallet Coin Info Flow](https://github.com/moontreeapp/moontree/issues/309)
