### ISSUE TITLE
[raven_front] Ability to Send RVN and RVN Assets

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#20]
**Describe the User Story:**
As an User
I want to Sending RVN and RVN Assets

**Describe What You'd Like:**
Much of the functionality for Sending RVN also applies to RVN Assets. such as being able to specify: address, scan address, fee level, send amount, send all, see the usd amount

**Story:**
- [x] https://github.com/moontreeapp/raven_front/issues/23
- [x] https://github.com/moontreeapp/raven_back/issues/31

**Tasks:**
- [x] https://github.com/moontreeapp/raven_front/issues/24
- [x] https://github.com/moontreeapp/raven_front/issues/21
- [ ] https://github.com/moontreeapp/raven_front/issues/4
- [ ] https://github.com/moontreeapp/raven_front/issues/75
- [x] https://github.com/moontreeapp/raven_front/issues/76
- [x] https://github.com/moontreeapp/raven_front/issues/77

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Send Flow](https://github.com/moontreeapp/moontree/issues/305)
