### ISSUE TITLE
[raven_front] Receive Ability

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#21]
**Describe the User Story:**
As an User
I want to Receive RVN and RVN Assets

**Describe What You'd Like:**
Much of the functionality for receiving RVN also applies to RVN Assets. such as: Qrcode, share, URI requesting how much, what kind of asset we want and what the note should be.

**Tasks:**
- [x] https://github.com/moontreeapp/raven_front/issues/18
- [x] https://github.com/moontreeapp/raven_front/issues/73
- [x] https://github.com/moontreeapp/raven_front/issues/74

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Receive Flow](https://github.com/moontreeapp/moontree/issues/302)
