### ISSUE TITLE
[raven_back] Build out a proper Test Suite

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#47]
**Is your feature request related to a problem? Please describe.**
As a dev we should have a proper test suite going into alpha, especially. We've written tests, but many became obsolete as things were changed, and tests were not kept up. But as the code base is maturing, we should have them especially in a continuous deployment environment.

**Describe the solution you'd like**
Not certain, we could get started by testing the pure functions we do have in utilities and services, but those are less likely to contain bugs anyway since they're simpler and more transparent than integration issues. so, it's a place to start, but we need to consider much more. Duane had the following thoughts

'''
meta stack — Today at 2:36 PM
What do you think is the first thing we need to do to get a suitable testing suite?

canadaduane — Today at 2:46 PM
Lots of thoughts... where my thoughts go first...

I think some of our code is hard to test right now--the more coupled any code is to other code, the more setup/teardown there will be when isolating pieces for tests. Coupling is the enemy of unit tests.

There's also the question of "Why isolate?" i.e. why not just run integration tests and make sure "everything works". The short answer is "combinatorial complexity". Especially where security is concerned, the ideal test suite is able to take tweezers to very small parts of the code base and analyze each aspect of its "most probable failure modes" (i.e. the edges or boundaries of a function such as e.g. 0, min, max, infinity, or zero-length strings, 64GB length strings, etc.). Also when (if?) we get really serious about testing for security's sake, we can employ fuzzers which automate the choosing of possibly-problematic-inputs so that it can test for memory leaks and such.

I don't think we need to achieve perfection (it's not worth it) but if we do want to move towards better coverage then reduced coupling makes things a lot easier (and less mental overhead). This implies some refactoring as we test. Fewer globals. Fewer side effects (more "pure functions" where sensible).

Where to start... I guess we should define our goals around testing. What do we care about most? Speed of delivering new features? (related:) Preventing regressions around wallet access, spending etc.? Making sure the UI is always responsive? etc.
'''

**Additional context**
I think we must discuss to find the most efficient way forward. I love the idea of decoupled concerns to the maximum degree possible, and the idea of building as pure functions as possible. I don't expect implementing a full coverage test suite requires an overhaul of existing data or code structures.

**Tasks:**
- [x] https://github.com/moontreeapp/raven_back/issues/57
- [x] https://github.com/moontreeapp/raven_back/issues/58
- [x] https://github.com/moontreeapp/raven_back/issues/59
