### ISSUE TITLE
[raven_back] Send Raven Assets

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#51]
**Is your feature request related to a problem? Please describe.**
Users should be able to send Raven Assets.

**Describe the solution you'd like**
We can send RVN by making a transaction, RVN asset sending transactions should also be supported by ravencoin_wallet

**Task:**
- [x] https://github.com/moontreeapp/raven_back/issues/2
- [x] https://github.com/moontreeapp/raven_back/issues/6
- [ ] https://github.com/moontreeapp/raven_back/issues/32
- [x] https://github.com/moontreeapp/raven_front/issues/26

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Send Flow](https://github.com/moontreeapp/moontree/issues/305)
